<?php

namespace ByExample\RecommandationsBundle\Repository;

use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\EntityRepository;
use ByExample\RecommandationsBundle\Entity\Algorithm;
use Doctrine\ORM\Query;
use \DateTime;

/**
 * RecommandationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecommandationRepository extends EntityRepository{

	public function addRecommandation(idalgo, $idutil, $arrayItem){
        $repository = $this->_em->getRepository('ByExampleDemoBundle:Utilisateur');
        $user = $repository->findOneById($idUtilisateur);

        $recom = new Recommandation();
        $recom->setDate(new DateTime());
        $recom->setIdalgorithm($idalgo);
        $recom->setIdutilisateur($idutil);
        foreach ($arrayItem as $item) {
        	 $repository = $this->_em->getRepository('ByExampleDemoBundle:Item');
        	 $recom->addIditem($repository->findOneById($item["id"]));
        }

		$this->_em->persist($recom);
		$this->_em->flush();

		$idRecom = $recom->getId();

	    return $idRecom;
	}

	





}
