<?php

namespace EnhancedProxya0301330_4828730ea97f44e5d33f42ad46418158bf1ded0f\__CG__\ByExample\DemoBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class UserRoleRestController__JMSInjector
{
    public static function inject($container) {
        require_once '/Applications/MAMP/htdocs/FOSRestBundleByExample-master/app/cache/dev/jms_diextra/proxies/EnhancedProxya0301330_4828730ea97f44e5d33f42ad46418158bf1ded0f-__CG__-ByExample-DemoBundle-Controller-UserRoleRestController.php';
        $d = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('ByExample\\DemoBundle\\Controller\\UserRoleRestController' => array('postRolesAction' => array(0 => 'security.access.method_interceptor'), 'getRolesAction' => array(0 => 'security.access.method_interceptor'), 'deleteRoleAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxya0301330_4894b995b67fb05b60fdcbe09f8f6827f11a0f1b\__CG__\ByExample\DemoBundle\Controller\UserRoleRestController();
        $instance->__CGInterception__setLoader($d);
        return $instance;
    }
}
