<?php

namespace ByExample\DemoBundle\Repository;

use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\EntityRepository;

/**
 * GenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreRepository extends EntityRepository
{
	public function findAll()
    {
        $rsm = new ResultSetMapping($em);
        $rsm->addEntityResult('ByExampleDemoBundle:Genre','g');
        $rsm->addScalarResult('id','id');
        $rsm->addScalarResult('libelle','libelle');
        $rsm->addScalarResult('urlCover', 'urlCover');

        $this->_em->flush();
        $this->_em->clear();

        $query = $this->_em->createNativeQuery('SELECT g.* FROM genre g', $rsm);
        $genre = $query->getResult();
        return $genre;
    }
}
