<?php

namespace ByExample\DemoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends EntityRepository
{
	public function findNoteByArtiste($idArtiste)
	{
       
		$query = $this->_em->createQuery('SELECT a.note FROM ByExampleDemoBundle:Artiste a WHERE a.id = :idArtiste')
        ->setParameter('idArtiste', $idArtiste);
        $note = $query->getResult();
        return $note;
	}

    public function findNoteByItem($idItem)
    {
       
        $query = $this->_em->createQuery('SELECT i.note FROM ByExampleDemoBundle:Item i WHERE i.id = :idItem')
        ->setParameter('idItem', $idItem);
        $note = $query->getResult();
        return $note;
    }
}
