<?php

namespace ByExample\DemoBundle\Repository;

use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends EntityRepository{

	public function findItemsBySessionId($id_session){
		$query=$this->_em->createQuery('SELECT partial i.{id,url,titre,note,duree,typeitem,nbvues,date,urlCover}, partial a.{id,nom}
	    FROM ByExampleDemoBundle:Session s JOIN s.idecoute e, ByExampleDemoBundle:Item i  LEFT JOIN i.idartiste a
        WHERE e.iditem = i.id AND s.id = :id_session')
	    ->setParameter("id_session",$id_session);
	    $items=$query->getResult(Query::HYDRATE_ARRAY);
	    return $items;
	}

}